<template>
  <div v-if="modelValue" class="mobile-modal"><div class="mobile-modal-card"><div class="modal-head"><h3>手动物料录入</h3><button class="modal-close" @click="close">✕</button></div><label v-if="form.pieceNo" class="form-label">单件码<input :value="form.pieceNo" disabled/></label><label class="form-label">名称<input v-model.trim="form.name" placeholder="请输入货品名称"/></label><label class="form-label">已有二级品类<select v-model="form.categoryId"><option value="">不选择（按标签自动创建）</option><option v-for="category in categories" :key="category.category_id" :value="String(category.category_id)">{{ category.name }}</option></select></label><label class="form-label">标签品类（可选）<input v-model.trim="form.categoryName" placeholder="扫码标签中的品类名称"/></label><p v-if="!form.categoryId && form.categoryName" class="muted small">提交后将自动创建或复用对应分类</p><label class="form-label">金重（g）<input v-model.number="form.goldWeight" type="number" min="0" step="0.001"/></label><label class="form-label">成本价（元）<input v-model.number="form.costPrice" type="number" min="0" step="0.01"/></label><label class="form-label">标签价（元）<input v-model.number="form.labelPrice" type="number" min="0" step="0.01"/></label><label class="form-label">证书号（可选）<input v-model.trim="form.certificateNo" placeholder="请输入证书号"/></label><p v-if="error" class="error">{{ error }}</p><div class="action-row"><button class="outline" @click="close">取消</button><button class="primary" @click="submit">加入清单</button></div></div></div>
</template>
<script setup>
import { reactive, ref, watch } from 'vue'
import { api } from '../api/request.js'
const props = defineProps({ modelValue: Boolean, initialBarcode: { type: String, default: '' }, initialData: { type: Object, default: () => ({}) } })
const emit = defineEmits(['update:modelValue', 'submit'])
const form = reactive({ name: '', categoryId: '', categoryName: '', goldWeight: null, costPrice: null, labelPrice: null, certificateNo: '', barcode: '', pieceNo: '' }); const categories = ref([]); const error = ref('')
watch(() => props.modelValue, async v => { if (v) { const seed = props.initialData || {}; Object.assign(form, { name: seed.name || '', categoryId: seed.categoryId || '', categoryName: seed.categoryName || '', goldWeight: seed.goldWeight ?? null, costPrice: seed.costPrice ?? null, labelPrice: seed.labelPrice ?? null, certificateNo: seed.certificateNo || '', barcode: props.initialBarcode || seed.barcode || '', pieceNo: String(seed.pieceNo || '').trim() }); error.value = ''; try { const rows = await api.goodsCategories(); categories.value = (Array.isArray(rows) ? rows : rows?.records || []).filter(row => Number(row.level) === 2 && Number(row.status ?? 1) === 1) } catch { categories.value = [] } } })
function close() { emit('update:modelValue', false) }
function submit() { if (!form.name) { error.value = '请输入货品名称'; return }; if (!form.categoryId && !String(form.categoryName || '').trim()) { error.value = '请选择二级品类，或填写扫码标签中的品类'; return }; if (form.goldWeight === null || !(Number(form.goldWeight) > 0)) { error.value = '请输入有效金重'; return }; if (form.costPrice === null || form.costPrice === '' || Number(form.costPrice) < 0) { error.value = '请输入有效成本价'; return }; if (form.labelPrice === null || form.labelPrice === '' || Number(form.labelPrice) < 0) { error.value = '请输入有效标签价'; return }; const category = categories.value.find(row => Number(row.category_id) === Number(form.categoryId)); emit('submit', { ...form, goldWeight: Number(form.goldWeight), costPrice: Number(form.costPrice), labelPrice: Number(form.labelPrice), categoryId: form.categoryId ? Number(form.categoryId) : null, categoryName: category?.name || String(form.categoryName || '').trim(), barcode: String(form.barcode || '').trim() }); close() }
</script>
