-- Dajin Store Management System, MySQL 8.0
-- 业务主键统一使用语义化名称；sys_store 仅使用 store_id 作为主键。
CREATE DATABASE IF NOT EXISTS dajin DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dajin;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS sys_store (store_id BIGINT PRIMARY KEY, store_name VARCHAR(100) NOT NULL, address VARCHAR(255), phone VARCHAR(30), logo VARCHAR(500), status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sys_role (role_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, role_name VARCHAR(50) NOT NULL, role_code VARCHAR(50) NOT NULL, description VARCHAR(255), permissions JSON, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_role_store_code(store_id,role_code));
CREATE TABLE IF NOT EXISTS sys_role_permission (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, role_code VARCHAR(50) NOT NULL, permission_code VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_role_permission(store_id,role_code,permission_code), KEY idx_role_permission_code(store_id,permission_code));
CREATE TABLE IF NOT EXISTS sys_user_permission (id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, user_id BIGINT NOT NULL, permission_code VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_user_permission(store_id,user_id,permission_code), KEY idx_user_permission_code(store_id,permission_code), KEY idx_user_permission_user(store_id,user_id));
CREATE TABLE IF NOT EXISTS sys_user (user_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, username VARCHAR(64) NOT NULL, password VARCHAR(255) NOT NULL, real_name VARCHAR(50) NOT NULL, role_id BIGINT NOT NULL, phone VARCHAR(30), id_card VARCHAR(32), entry_date DATE, remark VARCHAR(500), permission_initialized TINYINT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, version INT NOT NULL DEFAULT 0, UNIQUE KEY uk_user_store_username(store_id,username));
CREATE TABLE IF NOT EXISTS goods_category (category_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, category_code VARCHAR(50) NOT NULL, parent_id BIGINT DEFAULT 0, level TINYINT NOT NULL DEFAULT 1, sort INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_goods_category_store_code(store_id,category_code), KEY idx_goods_category_parent(store_id,parent_id,level,status));
CREATE TABLE IF NOT EXISTS goods (goods_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, barcode VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, category_id BIGINT NOT NULL, weight DECIMAL(10,3), cost_price DECIMAL(12,2) NOT NULL DEFAULT 0, sale_price DECIMAL(12,2), price_type TINYINT NOT NULL, gold_type VARCHAR(50) DEFAULT '足金', certificate_no VARCHAR(64), stock DECIMAL(12,3) NOT NULL DEFAULT 0, images JSON, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, version INT NOT NULL DEFAULT 0, UNIQUE KEY uk_goods_store_barcode(store_id,barcode), KEY idx_goods_category(store_id,category_id), KEY idx_goods_gold_type(store_id,gold_type));
CREATE TABLE IF NOT EXISTS process_item (process_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(30), base_fee DECIMAL(12,2) NOT NULL DEFAULT 0, process_steps JSON, duration INT, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS print_job (job_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, order_id BIGINT NOT NULL, order_no VARCHAR(32) NOT NULL, customer_name VARCHAR(64) NULL, customer_phone VARCHAR(32) NULL, job_type VARCHAR(20) NOT NULL DEFAULT 'PROCESSING', status VARCHAR(16) NOT NULL DEFAULT 'PENDING', created_by BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, printed_time DATETIME NULL, printed_by BIGINT NULL, ignored_time DATETIME NULL, ignored_by BIGINT NULL, KEY idx_print_store_status(store_id,status,create_time));
CREATE TABLE IF NOT EXISTS goods_piece (piece_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, goods_id BIGINT NOT NULL, piece_no VARCHAR(80) NOT NULL, image TEXT, status TINYINT NOT NULL DEFAULT 1, inbound_id BIGINT, sales_order_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_goods_piece_store_no (store_id, piece_no), KEY idx_piece_goods (store_id, goods_id, status), KEY idx_piece_inbound (inbound_id));
-- 2026-09-15 移动端转交前台：ALTER TABLE processing_order ADD COLUMN handover TINYINT NOT NULL DEFAULT 0, ADD COLUMN handover_time DATETIME NULL; ALTER TABLE sales_order ADD COLUMN handover TINYINT NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS processing_category (category_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL, category_code VARCHAR(32) NOT NULL, sort INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, created_by BIGINT, updated_by BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_processing_category_store_code(store_id,category_code), KEY idx_processing_category_store_status(store_id,status,sort));
CREATE TABLE IF NOT EXISTS processing_item (item_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, category_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, item_code VARCHAR(32) NOT NULL, labor_fee DECIMAL(12,2) NOT NULL DEFAULT 0, pricing_unit VARCHAR(10) NOT NULL DEFAULT '按件', processing_days SMALLINT NOT NULL DEFAULT 0, duration_text VARCHAR(30) NOT NULL DEFAULT '', process_steps VARCHAR(200) NOT NULL DEFAULT '', commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, remark VARCHAR(500), created_by BIGINT, updated_by BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_processing_item_store_code(store_id,item_code), KEY idx_processing_item_category(store_id,category_id,status));
CREATE TABLE IF NOT EXISTS processing_order (processing_order_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, order_no VARCHAR(32) NOT NULL, member_id BIGINT, customer_name VARCHAR(64) NOT NULL, customer_phone VARCHAR(32) NOT NULL, processing_item_id BIGINT NOT NULL, item_name_snapshot VARCHAR(100) NOT NULL, unit_labor_fee DECIMAL(12,2) NOT NULL DEFAULT 0, commission_rate_snapshot DECIMAL(5,2) NOT NULL DEFAULT 0, pricing_unit VARCHAR(10) NOT NULL DEFAULT '按件', billing_weight DECIMAL(10,3) NULL, quantity INT NOT NULL DEFAULT 1, labor_fee DECIMAL(12,2) NOT NULL DEFAULT 0, old_gold_weight DECIMAL(10,3), old_gold_fineness DECIMAL(6,4), store_gold_weight DECIMAL(10,3) NOT NULL DEFAULT 0, store_gold_fineness DECIMAL(6,4) NULL, store_gold_price DECIMAL(12,2) NOT NULL DEFAULT 0, store_gold_amount DECIMAL(12,2) NOT NULL DEFAULT 0, store_gold_goods_id BIGINT NULL, store_gold_deducted TINYINT NOT NULL DEFAULT 0, incoming_photos TEXT NULL, weigh_photos TEXT NULL, pickup_photos TEXT NULL, finished_weight DECIMAL(10,3) NULL, finished_fineness DECIMAL(6,4) NULL, recovered_weight DECIMAL(10,3) NULL, loss_weight DECIMAL(10,3) NULL, loss_permille DECIMAL(8,2) NULL, loss_over TINYINT NOT NULL DEFAULT 0, loss_note VARCHAR(500) NULL, loss_time DATETIME NULL, residual_material_type VARCHAR(50), residual_gold_weight DECIMAL(10,3), residual_gold_fineness DECIMAL(6,4), residual_gold_handling VARCHAR(24) NOT NULL DEFAULT 'TAKE_AWAY', residual_gold_deduction DECIMAL(12,2) NOT NULL DEFAULT 0, residual_material_recorded TINYINT NOT NULL DEFAULT 0, due_amount DECIMAL(12,2) NOT NULL DEFAULT 0, paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0, pickup_date DATE, craftsman_id BIGINT, status VARCHAR(24) NOT NULL DEFAULT 'PENDING', remark VARCHAR(500), handover TINYINT NOT NULL DEFAULT 0, handover_time DATETIME NULL, source_sales_order_id BIGINT, created_by BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, completed_time DATETIME NULL, picked_up_time DATETIME NULL, version INT NOT NULL DEFAULT 0, UNIQUE KEY uk_processing_order_store_no(store_id,order_no), KEY idx_processing_order_status(store_id,status,create_time), KEY idx_processing_order_craftsman(store_id,craftsman_id,status));
CREATE TABLE IF NOT EXISTS processing_payment (payment_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, processing_order_id BIGINT NOT NULL, payment_type VARCHAR(16) NOT NULL, amount DECIMAL(12,2) NOT NULL, pay_method VARCHAR(50) NOT NULL, client_request_id VARCHAR(64), operator_id BIGINT, remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_processing_payment_client(store_id,client_request_id), KEY idx_processing_payment_order(store_id,processing_order_id,create_time));
CREATE TABLE IF NOT EXISTS processing_commission (commission_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, processing_order_id BIGINT NOT NULL, employee_id BIGINT NOT NULL, commission_base DECIMAL(12,2) NOT NULL DEFAULT 0, commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0, commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'PENDING', paid_at DATETIME NULL, paid_by BIGINT NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_processing_commission_order_employee(processing_order_id,employee_id), KEY idx_processing_commission_status(store_id,status,employee_id));
CREATE TABLE IF NOT EXISTS gold_price (price_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, price_type VARCHAR(30) NOT NULL, price DECIMAL(12,2) NOT NULL, date DATE NOT NULL, operator_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_gold_store_type_date(store_id,price_type,date,price_id));
CREATE TABLE IF NOT EXISTS stock_in (stock_in_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, bill_no VARCHAR(32) NOT NULL, type VARCHAR(30) NOT NULL, goods_id BIGINT, qty DECIMAL(12,3) NOT NULL DEFAULT 0, cost DECIMAL(12,2) NOT NULL DEFAULT 0, operator_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_stockin_store_bill(store_id,bill_no));
CREATE TABLE IF NOT EXISTS stock_supplier (supplier_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, supplier_name VARCHAR(100) NOT NULL, supplier_code VARCHAR(50) NOT NULL, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_stock_supplier_store_code(store_id,supplier_code), KEY idx_stock_supplier_store_status(store_id,status,supplier_name));
CREATE TABLE IF NOT EXISTS stock_inbound (inbound_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, inbound_no VARCHAR(40) NOT NULL, inbound_type VARCHAR(24) NOT NULL, source_id BIGINT NULL, remark VARCHAR(500), status VARCHAR(16) NOT NULL DEFAULT 'COMPLETED', total_quantity DECIMAL(12,3) NOT NULL DEFAULT 0, total_weight DECIMAL(12,3) NOT NULL DEFAULT 0, total_amount DECIMAL(14,2) NOT NULL DEFAULT 0, operator_id BIGINT, client_request_id VARCHAR(64), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_stock_inbound_store_no(store_id,inbound_no), UNIQUE KEY uk_stock_inbound_client(store_id,client_request_id), KEY idx_stock_inbound_store_time(store_id,create_time), KEY idx_stock_inbound_status(store_id,status));
CREATE TABLE IF NOT EXISTS stock_inbound_item (inbound_item_id BIGINT PRIMARY KEY AUTO_INCREMENT, inbound_id BIGINT NOT NULL, store_id BIGINT NOT NULL, goods_id BIGINT NULL, barcode VARCHAR(64) NOT NULL, name VARCHAR(100) NOT NULL, category_id BIGINT NULL, gold_weight DECIMAL(12,3) NULL, label_price DECIMAL(14,2) NOT NULL DEFAULT 0, certificate_no VARCHAR(64), quantity DECIMAL(12,3) NOT NULL DEFAULT 1, images JSON NULL, piece_nos JSON NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_stock_inbound_item_inbound(store_id,inbound_id), KEY idx_stock_inbound_item_goods(store_id,goods_id));
CREATE TABLE IF NOT EXISTS stock_out (stock_out_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, bill_no VARCHAR(32) NOT NULL, type VARCHAR(30) NOT NULL, goods_id BIGINT, qty DECIMAL(12,3) NOT NULL DEFAULT 0, reason VARCHAR(255), operator_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_stockout_store_bill(store_id,bill_no));
CREATE TABLE IF NOT EXISTS stock_check (check_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, bill_no VARCHAR(32) NOT NULL, scope_type VARCHAR(24) NOT NULL DEFAULT 'GOODS', scope_id BIGINT NULL, remark VARCHAR(500), client_request_id VARCHAR(64), status TINYINT NOT NULL DEFAULT 1, total_diff DECIMAL(12,3) NOT NULL DEFAULT 0, detail JSON, operator_id BIGINT, approver_id BIGINT, approve_remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_stockcheck_store_bill(store_id,bill_no), UNIQUE KEY uk_stock_check_client(store_id,client_request_id), KEY idx_stock_check_scope(store_id,status,scope_type,scope_id), KEY idx_stock_check_operator_time(store_id,operator_id,create_time));
CREATE TABLE IF NOT EXISTS old_material (material_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, material_type VARCHAR(50) NOT NULL, weight DECIMAL(10,3) NOT NULL, purity DECIMAL(6,4) NOT NULL, source VARCHAR(100), value DECIMAL(12,2) NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, direction TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, version INT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS old_material_type (type_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(50) NOT NULL, sort INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_old_material_type_store_name(store_id,name), KEY idx_old_material_type_store_status(store_id,status,sort));
CREATE TABLE IF NOT EXISTS sales_order (order_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, order_no VARCHAR(32) NOT NULL, member_id BIGINT, total_amount DECIMAL(12,2) NOT NULL DEFAULT 0, discount DECIMAL(5,2) NOT NULL DEFAULT 1, old_material_deduct DECIMAL(12,2) NOT NULL DEFAULT 0, old_material_excess DECIMAL(12,2) NOT NULL DEFAULT 0, old_material_payout_method VARCHAR(50), labor_fee DECIMAL(12,2) NOT NULL DEFAULT 0, pay_amount DECIMAL(12,2) NOT NULL DEFAULT 0, pay_method VARCHAR(50), cashier_id BIGINT, sales_id BIGINT, approval_id BIGINT, status TINYINT NOT NULL DEFAULT 3, handover TINYINT NOT NULL DEFAULT 0, remark VARCHAR(500), client_request_id VARCHAR(64), shift_no VARCHAR(48), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, paid_time DATETIME NULL, commission_rate_snapshot DECIMAL(10,6) NULL, version INT NOT NULL DEFAULT 0, UNIQUE KEY uk_order_store_no(store_id,order_no), UNIQUE KEY uk_order_store_client(store_id,client_request_id), KEY idx_order_store_create(store_id,create_time), KEY idx_order_shift(store_id,shift_no));
CREATE TABLE IF NOT EXISTS sales_order_item (order_item_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, order_id BIGINT NOT NULL, goods_id BIGINT, item_name VARCHAR(100) NOT NULL, weight DECIMAL(10,3), unit_price DECIMAL(12,2) NOT NULL DEFAULT 0, labor_fee DECIMAL(12,2) NOT NULL DEFAULT 0, qty DECIMAL(12,3) NOT NULL DEFAULT 1, subtotal DECIMAL(12,2) NOT NULL DEFAULT 0, cost_snapshot DECIMAL(14,2), piece_nos JSON NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_order_item(store_id,order_id));
CREATE TABLE IF NOT EXISTS recycle_order (recycle_order_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, bill_no VARCHAR(32) NOT NULL, member_id BIGINT, material_type VARCHAR(50), weight DECIMAL(10,3) NOT NULL, purity DECIMAL(6,4) NOT NULL, deduct_loss DECIMAL(12,2) NOT NULL DEFAULT 0, total_amount DECIMAL(12,2) NOT NULL DEFAULT 0, pay_method VARCHAR(50), status TINYINT NOT NULL DEFAULT 1, approver_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_recycle_store_bill(store_id,bill_no));
CREATE TABLE IF NOT EXISTS trade_in (trade_in_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, bill_no VARCHAR(32) NOT NULL, member_id BIGINT, old_material_info JSON, new_goods_info JSON, diff_amount DECIMAL(12,2) NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, approval_id BIGINT, operator_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_tradein_store_bill(store_id,bill_no), KEY idx_tradein_operator_time(store_id,operator_id,create_time));
CREATE TABLE IF NOT EXISTS member (member_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, phone VARCHAR(30) NOT NULL, tags JSON, balance DECIMAL(12,2) NOT NULL DEFAULT 0, points INT NOT NULL DEFAULT 0, total_consume DECIMAL(12,2) NOT NULL DEFAULT 0, source VARCHAR(50), sales_id BIGINT, birthday DATE NULL, gender VARCHAR(16) NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_member_store_phone(store_id,phone), KEY idx_member_phone(store_id,phone), KEY idx_member_birthday(store_id,birthday));
CREATE TABLE IF NOT EXISTS member_consume (consume_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, member_id BIGINT NOT NULL, order_id BIGINT, amount DECIMAL(12,2) NOT NULL DEFAULT 0, consume_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_member_consume(store_id,member_id));
CREATE TABLE IF NOT EXISTS member_balance_record (record_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, member_id BIGINT NOT NULL, amount DECIMAL(12,2) NOT NULL, balance_after DECIMAL(12,2) NOT NULL, type VARCHAR(30) NOT NULL, reference_no VARCHAR(64) NOT NULL, operator_id BIGINT, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_balance_ref(store_id,type,reference_no), KEY idx_balance_member(store_id,member_id,record_id));
CREATE TABLE IF NOT EXISTS visit_task (task_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, member_id BIGINT NOT NULL, sales_id BIGINT NOT NULL, order_id BIGINT NULL, order_no_snapshot VARCHAR(32) NULL, amount_snapshot DECIMAL(12,2) NULL, purchase_time_snapshot DATETIME NULL, phone_snapshot VARCHAR(32) NULL, gender_snapshot VARCHAR(16) NULL, followup_no INT NOT NULL DEFAULT 0, visit_type VARCHAR(30), plan_time DATETIME, status TINYINT NOT NULL DEFAULT 1, record VARCHAR(1000), call_result VARCHAR(24) NULL, call_started_at DATETIME NULL, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_visit_order_type(store_id,order_id,visit_type,followup_no));
CREATE TABLE IF NOT EXISTS approval (approval_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, type VARCHAR(30) NOT NULL, biz_id BIGINT NOT NULL, applicant_id BIGINT, amount DECIMAL(12,2), reason VARCHAR(500), status TINYINT NOT NULL DEFAULT 1, approver_id BIGINT, approve_remark VARCHAR(500), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, approve_time DATETIME, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_approval_pending(store_id,status));
CREATE TABLE IF NOT EXISTS commission_rule (rule_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, type VARCHAR(30) NOT NULL, rate DECIMAL(8,4) NOT NULL DEFAULT 0, `condition` JSON, description VARCHAR(500), status TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS commission_record (record_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, user_id BIGINT NOT NULL, month CHAR(7) NOT NULL, sales_amount DECIMAL(12,2) NOT NULL DEFAULT 0, commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0, detail JSON, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_commission_month(store_id,month));
CREATE TABLE IF NOT EXISTS finance_record (finance_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, type VARCHAR(20) NOT NULL, category VARCHAR(30), amount DECIMAL(12,2) NOT NULL DEFAULT 0, pay_method VARCHAR(50), related_bill_no VARCHAR(32), operator_id BIGINT, remark VARCHAR(500), shift_no VARCHAR(48), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_finance_date(store_id,create_time), KEY idx_finance_method_time(store_id,pay_method,create_time), KEY idx_finance_shift(store_id,shift_no));
CREATE TABLE IF NOT EXISTS print_template (template_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(30) NOT NULL, content JSON, is_default TINYINT NOT NULL DEFAULT 0, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS operation_log (log_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, user_id BIGINT, module VARCHAR(50), action VARCHAR(50), content TEXT, client_request_id VARCHAR(64), ip VARCHAR(64), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_log_store_time(store_id,create_time), UNIQUE KEY uk_log_idempotency(store_id,module,client_request_id));
CREATE TABLE IF NOT EXISTS sys_config (config_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, config_group VARCHAR(50) NOT NULL DEFAULT 'SYSTEM', config_key VARCHAR(100) NOT NULL, config_value VARCHAR(2000) NOT NULL, description VARCHAR(255), config_sort INT NOT NULL DEFAULT 0, enabled TINYINT NOT NULL DEFAULT 1, create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_config_store_group_key(store_id,config_group,config_key));
CREATE TABLE IF NOT EXISTS pay_channel (channel_id BIGINT PRIMARY KEY AUTO_INCREMENT, store_id BIGINT NOT NULL, channel_name VARCHAR(50) NOT NULL, channel_code VARCHAR(50) NOT NULL, sort INT NOT NULL DEFAULT 0, status TINYINT NOT NULL DEFAULT 1, icon VARCHAR(255), create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_pay_channel_store_code(store_id,channel_code));

INSERT IGNORE INTO sys_store(store_id,store_name,address,status) VALUES (1,'默认门店','',1);
INSERT IGNORE INTO sys_role(role_id,store_id,role_name,role_code,description,permissions,status) VALUES (1,1,'管理员','ADMIN','系统全部权限','["*"]',1),(2,1,'店长','MANAGER','门店经营及管理权限','["stock:inbound:create"]',1),(3,1,'前台','CASHIER','收银、会员及交班权限','["stock:inbound:create"]',1),(4,1,'销售','SALES','个人业绩、入库盘点、回收、加工、会员及回访权限','["dashboard:view","goods:search","stock:inbound:create","stock:check:view","stock:check:create","stock:check:submit","member:view","member:create","member:follow","processing:view","recycle:view","report:view","notification:view"]',1),(5,1,'打金师傅','CRAFTSMAN','加工订单承接、损耗与提成归属','["processing:view"]',1);
-- 开发种子密码为 admin；首次登录后后端会自动升级为 BCrypt 哈希。
INSERT IGNORE INTO sys_user(user_id,store_id,username,password,real_name,role_id,status) VALUES
 (1,1,'admin','admin','系统管理员',1,1),
 (2,1,'manager','admin','店长演示',2,1),
 (3,1,'sales','admin','销售演示',4,1),
 (4,1,'cashier','admin','前台演示',3,1);
INSERT IGNORE INTO sys_config(store_id,config_group,config_key,config_value,description,config_sort) VALUES (1,'SYSTEM','discount_threshold','0.85','低于此折扣需审批',1),(1,'SYSTEM','recycle_approval_limit','10000','超过此金额的大额回收需审批',2),(1,'SYSTEM','default_commission_rate','0.01','默认销售提成比例',3),(1,'SYSTEM','old_material_types','[{"name":"足金999","status":1},{"name":"足金990","status":1},{"name":"22K金","status":1},{"name":"18K金","status":1},{"name":"14K金","status":1},{"name":"铂金950","status":1},{"name":"铂金900","status":1},{"name":"纯银","status":1}]','旧料类型（库存类型管理）',4),(1,'SYSTEM','gold_metal_types','[{"name":"足金","code":"GOLD","purity":99.9,"price":612,"sort":1,"status":1},{"name":"回收金价","code":"RECYCLE","purity":99.9,"price":578,"sort":2,"status":1},{"name":"18K","code":"18K","purity":75,"price":428,"sort":3,"status":1},{"name":"铂金","code":"PLATINUM","purity":95,"price":0,"sort":4,"status":1},{"name":"银","code":"SILVER","purity":99.9,"price":0,"sort":5,"status":1},{"name":"银回收价","code":"SILVER_RECYCLE","purity":99.9,"price":0,"sort":6,"status":1}]','贵金属类型（JSON数组）',5);
INSERT IGNORE INTO pay_channel(store_id,channel_name,channel_code,sort,status,icon) VALUES (1,'现金','CASH',1,1,'cash'),(1,'微信','WECHAT',2,1,'wechat'),(1,'支付宝','ALIPAY',3,1,'alipay'),(1,'银行卡','BANK',4,1,'bank'),(1,'储值','BALANCE',5,1,'balance'),(1,'组合','COMBINATION',6,1,'combination');
INSERT IGNORE INTO stock_supplier(store_id,supplier_name,supplier_code,status) SELECT store_id,'默认供应商','DEFAULT_SUPPLIER',1 FROM sys_store;
INSERT IGNORE INTO goods_category(category_id,store_id,name,category_code,parent_id,level,sort,status) VALUES (1,1,'成品黄金','FINISHED_GOLD',0,1,1,1),(2,1,'K金','K_GOLD',0,1,2,1),(3,1,'银饰','SILVER',0,1,3,1),(4,1,'加工','PROCESSING',0,1,4,1);
INSERT IGNORE INTO goods(goods_id,store_id,barcode,name,category_id,weight,cost_price,sale_price,price_type,stock,status,images) VALUES (1,1,'697000000001','古法传承手镯',1,32.500,553.85,612,1,8,1,'[]'),(2,1,'697000000002','足金素圈戒指',1,5.200,480.77,612,1,23,1,'[]'),(3,1,'697000000003','幸运转运珠',1,2.100,500,698,2,15,1,'[]'),(4,1,'697000000004','S925银耳钉',3,1.800,100,268,2,31,1,'[]'),(5,1,'697000000005','手工编绳加工',4,NULL,20,58,2,999,1,'[]'),(6,1,'697000000006','18K金项链',2,8.600,441.86,428,1,6,1,'[]');
INSERT IGNORE INTO gold_price(price_id,store_id,price_type,price,date,operator_id) VALUES (1,1,'足金',612,CURDATE(),1),(2,1,'回收金价',578,CURDATE(),1),(3,1,'18K',428,CURDATE(),1);
INSERT IGNORE INTO processing_category(store_id,name,category_code,sort,status,created_by,updated_by) VALUES (1,'首饰加工','JEWELRY',1,1,1,1),(1,'摆件加工','ORNAMENT',2,1,1,1),(1,'维修保养','REPAIR',3,1,1,1),(1,'定制加工','CUSTOM',4,1,1,1);
INSERT IGNORE INTO processing_item(store_id,category_id,name,item_code,labor_fee,processing_days,commission_rate,status,created_by,updated_by) SELECT 1,category_id,'手镯加工','BRACELET_PROCESS',200,3,10,1,1,1 FROM processing_category WHERE store_id=1 AND category_code='JEWELRY';
INSERT IGNORE INTO processing_item(store_id,category_id,name,item_code,labor_fee,processing_days,commission_rate,status,created_by,updated_by) SELECT 1,category_id,'项链加工','NECKLACE_PROCESS',150,2,10,1,1,1 FROM processing_category WHERE store_id=1 AND category_code='JEWELRY';
INSERT IGNORE INTO processing_item(store_id,category_id,name,item_code,labor_fee,processing_days,commission_rate,status,created_by,updated_by) SELECT 1,category_id,'戒指加工','RING_PROCESS',100,2,10,1,1,1 FROM processing_category WHERE store_id=1 AND category_code='JEWELRY';
INSERT IGNORE INTO processing_item(store_id,category_id,name,item_code,labor_fee,processing_days,commission_rate,status,created_by,updated_by) SELECT 1,category_id,'焊接','WELDING',50,1,15,1,1,1 FROM processing_category WHERE store_id=1 AND category_code='REPAIR';
INSERT IGNORE INTO processing_item(store_id,category_id,name,item_code,labor_fee,processing_days,commission_rate,status,created_by,updated_by) SELECT 1,category_id,'改圈','RING_RESIZE',30,1,15,1,1,1 FROM processing_category WHERE store_id=1 AND category_code='REPAIR';
INSERT IGNORE INTO processing_item(store_id,category_id,name,item_code,labor_fee,processing_days,commission_rate,status,created_by,updated_by) SELECT 1,category_id,'抛光','POLISH',20,1,15,1,1,1 FROM processing_category WHERE store_id=1 AND category_code='REPAIR';
