<template>
  <div class="shell"><header class="topbar"><button class="back" @click="router.back()">‹</button><div><strong>经营日报</strong><span class="store">{{ dateText }}</span></div><button class="icon-btn" @click="load">刷新</button></header>
    <main class="content page"><label class="date-field">日报日期<input v-model="dateValue" type="date" @change="load"/></label>
      <div v-if="loading" class="empty">加载中...</div><div v-else-if="error" class="empty"><span>{{ error }}</span><button class="outline" @click="load">重试</button></div>
      <template v-else><div class="kpi-grid"><Kpi label="营业额(含加工)" :value="money(summary.turnover ?? summary.sales_amount ?? summary.amount)"/><Kpi label="毛利" :value="money(summary.gross_profit)"/><Kpi label="订单数" :value="`${summary.order_count || 0} 单`"/><Kpi label="客单价" :value="money(summary.avg_order)"/></div><div class="kpi-grid"><Kpi label="回收克重" :value="`${Number(recycle.weight||summary.recycle_weight||0).toFixed(3)}g`"/><Kpi label="回收金额" :value="money(recycle.amount)"/><Kpi label="以旧换新" :value="`${recycle.trade_in_count || 0} 单`"/><Kpi label="待处理" :value="`${pendingCount} 笔`"/></div>
        <Panel title="销售趋势"><div v-if="trend.length" class="report-bars"><div v-for="r in trend" :key="r.day||r.date" class="report-bar-col"><span>{{ shortMoney(r.amount||r.revenue) }}</span><i :style="{height:`${barHeight(r.amount||r.revenue)}%`}"></i><small>{{ String(r.day||r.date).slice(5,10) }}</small></div></div><div v-else class="empty">暂无趋势数据</div></Panel>
        <Panel title="员工排行"><div v-if="employees.length" v-for="(row,i) in employees" :key="row.user_id||row.employee_id||i" class="rank-row"><span class="rank-no">{{ i+1 }}</span><span>{{ row.name || row.employee_name || row.real_name || '员工' }}</span><strong>{{ money(row.amount || row.sales_amount) }}</strong><small>{{ row.order_count || 0 }} 单 · 提成 {{ money(row.commission) }}</small></div><div v-else class="empty">暂无员工数据</div></Panel>
        <Panel title="待处理事项"><button v-if="auth.can('processing:view') && (pendingCount || Number(stats.outstanding||0))" class="todo-entry rank-row" @click="router.push('/todo')"><span>未完成 {{ pendingCount }} 笔 · 未收尾款 {{ money(stats.outstanding) }}</span><strong>去处理 ›</strong></button><div v-else-if="pendingCount || Number(stats.outstanding||0)" class="pending-list"><div class="rank-row"><span>未完成订单</span><strong>{{ pendingCount }} 笔</strong><small>请在审批或加工模块跟进</small></div><div class="rank-row"><span>未收尾款</span><strong>{{ money(stats.outstanding) }}</strong><small>加工订单应收余额</small></div></div><div v-else class="empty">今日暂无待处理事项</div></Panel>
      </template>
    </main>
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { api } from '../api/request.js'; import { useAuthStore } from '../stores/auth.js'; import Kpi from '../components/Kpi.vue'; import Panel from '../components/Panel.vue'
const router=useRouter(); const auth=useAuthStore(); const dateValue=ref(new Date().toISOString().slice(0,10)); const loading=ref(false); const error=ref(''); const overview=ref({}); const recycle=ref({}); const stats=ref({}); const processing=ref([])
const summary=computed(()=>overview.value.summary||overview.value||{}); const trend=computed(()=>overview.value.trend||[]); const employees=computed(()=>overview.value.employees||overview.value.ranking||[]); const dateText=computed(()=>dateValue.value); const pendingCount=computed(()=>processing.value.filter(o=>!['PICKED_UP','COMPLETED'].includes(String(o.status))).length); const money=v=>`¥${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`; const shortMoney=v=>{const n=Number(v||0);return n>=10000?`¥${(n/10000).toFixed(1)}万`:`¥${Math.round(n)}`}; const barHeight=v=>{const max=Math.max(...trend.value.map(x=>Number(x.amount||x.revenue||0)),1);return Math.max(8,Number(v||0)/max*100)}
async function load(){loading.value=true;error.value='';try{const params={timeType:'custom',startDate:dateValue.value,endDate:dateValue.value};const [o,r,p,s]=await Promise.all([api.reportOverview(params),api.reportRecycle(params),api.processingOrders({start:dateValue.value,end:dateValue.value}),api.processingStatistics({from:dateValue.value,to:dateValue.value})]);overview.value=o||{};recycle.value=r||{};processing.value=Array.isArray(p)?p:(p?.records||[]);stats.value=s||{}}catch(e){error.value=e?.message||'经营日报加载失败'}finally{loading.value=false}}
onMounted(load)
</script>
<style scoped>
.date-field{display:flex;align-items:center;justify-content:space-between;gap:10px;font-size:12px;color:var(--ink-2);margin-bottom:12px}.date-field input{min-height:44px;border:1px solid #dfe3e8;border-radius:8px;padding:0 10px;background:#fff}.pending-list{font-size:13px}
.todo-entry{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;background:#fff;border:1px solid var(--line);border-radius:8px;padding:12px;font-size:13px;color:var(--ink-2);text-align:left}.todo-entry strong{color:var(--gold-deep);white-space:nowrap}
</style>
