<template>
  <div class="shell"><DesignHeader title="经营日报" :subtitle="dateText" :back="true" @back="router.back()"><button class="icon-btn" @click="load">刷新</button></DesignHeader>
    <main class="content page"><label class="date-field">日报日期<input v-model="dateValue" type="date" @change="load"/></label>
      <EmptyState v-if="loading" title="加载中..." /><EmptyState v-else-if="error" title=""><span>{{ error }}</span><button class="outline" @click="load">重试</button></EmptyState>
      <EmptyState v-else-if="!auth.can('report:daily')" title="当前账号未开启经营日报" />
      <template v-else><div class="kpi-grid"><Kpi :label="auth.can('report:processing') ? '营业额(含加工)' : '销售营业额'" :value="money(summary.turnover ?? summary.sales_amount ?? summary.amount)"/><Kpi v-if="summary.gross_profit != null" label="毛利" :value="money(summary.gross_profit)"/><Kpi label="订单数" :value="`${summary.order_count || 0} 单`"/><Kpi label="客单价" :value="money(summary.avg_order ?? Number(summary.amount||0)/Math.max(1,Number(summary.order_count||0)))"/></div><div class="kpi-grid"><Kpi v-if="auth.can('report:recycle')" label="回收克重" :value="`${Number(recycle.weight||summary.recycle_weight||0).toFixed(3)}g`"/><Kpi v-if="auth.can('report:recycle')" label="回收金额" :value="money(recycle.amount)"/><Kpi v-if="auth.can('report:recycle')" label="以旧换新" :value="`${recycle.trade_in_count || 0} 单`"/><Kpi label="待处理" :value="`${pendingCount} 笔`"/></div>
        <Panel v-if="auth.can('report:store-performance') && trend.length" title="销售趋势"><div v-if="trend.length" class="report-bars"><div v-for="r in trend" :key="r.day||r.date" class="report-bar-col"><span>{{ shortMoney(r.amount||r.revenue) }}</span><i :style="{height:`${barHeight(r.amount||r.revenue)}%`}"></i><small>{{ String(r.day||r.date).slice(5,10) }}</small></div></div><EmptyState v-else title="暂无趋势数据" /></Panel>
        <Panel v-if="auth.can('report:store-performance')" title="员工排行"><div v-if="employees.length" v-for="(row,i) in employees" :key="row.user_id||row.employee_id||i" class="rank-row"><span class="rank-no">{{ i+1 }}</span><span>{{ row.name || row.employee_name || row.real_name || '员工' }}</span><strong>{{ money(row.amount || row.sales_amount) }}</strong><small>{{ row.order_count || 0 }} 单 <template v-if="auth.can('report:commission')">· 提成 {{ money(row.commission) }}</template></small></div><EmptyState v-else title="暂无员工数据" /></Panel>
        <Panel title="待处理事项"><button v-if="auth.can('processing:view') && (pendingCount || Number(stats.outstanding||0))" class="todo-entry rank-row" @click="router.push('/todo')"><span>未完成 {{ pendingCount }} 笔 <template v-if="auth.can('report:processing')">· 未收尾款 {{ money(stats.outstanding) }}</template></span><strong>去处理 ›</strong></button><div v-else-if="pendingCount || Number(stats.outstanding||0)" class="pending-list"><div class="rank-row"><span>未完成订单</span><strong>{{ pendingCount }} 笔</strong><small>请在审批或加工模块跟进</small></div><div class="rank-row"><span>未收尾款</span><strong>{{ money(stats.outstanding) }}</strong><small>加工订单应收余额</small></div></div><EmptyState v-else title="今日暂无待处理事项" /></Panel>
      </template>
    </main>
  </div>
</template>
<script setup>
import EmptyState from '../components/EmptyState.vue'

import DesignHeader from '../components/DesignHeader.vue'

import { computed, onMounted, onBeforeUnmount, ref, watch } from 'vue'; import { useRouter } from 'vue-router'; import { api } from '../api/request.js'; import { useAuthStore } from '../stores/auth.js'; import Kpi from '../components/Kpi.vue'; import Panel from '../components/Panel.vue'; import { reportDate } from '../utils/reportRange.js'
const router=useRouter(); const auth=useAuthStore(); const dateValue=ref(reportDate()); const loading=ref(false); const error=ref(''); const overview=ref({}); const recycle=ref({}); const stats=ref({}); const processing=ref([])
const summary=computed(()=>overview.value.summary||overview.value||{}); const trend=computed(()=>overview.value.trend||[]); const employees=computed(()=>overview.value.employees||overview.value.ranking||[]); const dateText=computed(()=>dateValue.value); const pendingCount=computed(()=>processing.value.filter(o=>!['PICKED_UP','COMPLETED'].includes(String(o.status))).length); const money=v=>`¥${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`; const shortMoney=v=>{const n=Number(v||0);return n>=10000?`¥${(n/10000).toFixed(1)}万`:`¥${Math.round(n)}`}; const barHeight=v=>{const max=Math.max(...trend.value.map(x=>Number(x.amount||x.revenue||0)),1);return Math.max(8,Number(v||0)/max*100)}
let loadVersion=0
async function load(){const version=++loadVersion;overview.value={};recycle.value={};stats.value={};processing.value=[];if(!auth.can('report:daily')){loading.value=false;return}const scope=JSON.stringify(auth.user?.permissions);loading.value=true;error.value='';try{const params={timeType:'custom',startDate:dateValue.value,endDate:dateValue.value};const [o,r,p,s]=await Promise.all([auth.can('report:store-performance')?api.reportOverview(params):api.reportDaily({date:dateValue.value}),auth.can('report:recycle')?api.reportRecycle(params):Promise.resolve({}),auth.can('processing:view')?api.processingOrders({start:dateValue.value,end:dateValue.value}):Promise.resolve([]),auth.can('report:processing')?api.processingStatistics({from:dateValue.value,to:dateValue.value}):Promise.resolve({})]);if(version!==loadVersion||scope!==JSON.stringify(auth.user?.permissions)||!auth.can('report:daily'))return;overview.value=o||{};recycle.value=r||{};processing.value=Array.isArray(p)?p:(p?.records||[]);stats.value=s||{}}catch(e){if(version===loadVersion)error.value=e?.message||'经营日报加载失败'}finally{if(version===loadVersion)loading.value=false}}
onMounted(load)
watch(()=>JSON.stringify(auth.user?.permissions),load)
onBeforeUnmount(()=>{loadVersion++})
</script>
<style scoped>
.date-field{display:flex;align-items:center;justify-content:space-between;gap:10px;font-size:12px;color:var(--ink-2);margin-bottom:12px}.date-field input{min-height:44px;border:1px solid var(--line);border-radius:var(--r-md);padding:0 10px;background:var(--card)}.pending-list{font-size:13px}
.todo-entry{display:flex;align-items:center;justify-content:space-between;gap:8px;width:100%;background:var(--card);border:1px solid var(--line);border-radius:var(--r-md);padding:12px;font-size:13px;color:var(--ink-2);text-align:left}.todo-entry strong{color:var(--gold-deep);white-space:nowrap}
</style>
