<template>
  <div class="shell"><header class="topbar"><button class="back" @click="router.back()">‹</button><strong>金价设置</strong><button class="outline" :disabled="loading" @click="load">刷新</button></header><main class="content page">
    <p v-if="!auth.can('gold:manage')" class="error">当前账号没有金价管理权限。</p>
    <template v-else><p class="muted">管理员调整的是卖价加价和回收扣减，行情由服务端获取。保存后管理端、收银端和手机端同步。</p><article v-for="row in types" :key="row.type_id || row.type_code" class="panel setting-card"><div class="setting-head"><div><h3>{{ row.type_name }}</h3><small>{{ row.baseInstrument === 'Ag_TD' ? '白银 Ag(T+D)' : '黄金 Au(T+D)' }} · 基准 ¥{{ money(row.basePrice) }}/g</small></div><span class="status" :class="statusClass(row.marketStatus)">{{ statusText(row.marketStatus) }}</span></div><div class="quote-line"><span>卖价 <b>¥{{ money(row.salePrice) }}/g</b></span><span>回收价 <b>¥{{ money(row.recyclePrice) }}/g</b></span></div><div class="form-grid"><label>定价方式<select v-model="row.pricingMode"><option value="MANUAL">手动</option><option value="AUTO">自动</option></select></label><label>基准品种<select v-model="row.baseInstrument"><option value="Au_TD">黄金 Au(T+D)</option><option value="Ag_TD">白银 Ag(T+D)</option></select></label><label>成色系数<input v-model.number="row.purityCoefficient" type="number" min="0.0001" max="1" step="0.000001" /></label><label>卖价加价<input v-model.number="row.markup" type="number" min="0" step="0.01" /></label><label>回收扣减<input v-model.number="row.recycleDeduction" type="number" min="0" step="0.01" /></label><label>取整规则<select v-model="row.roundingRule"><option value="NONE">不取整</option><option value="TENTH">到角</option><option value="YUAN">到元</option><option value="TAIL_8">尾数 .8</option><option value="TAIL_9">尾数 .9</option></select></label></div><div class="formula">基准 {{ money(row.basePrice) }} × 成色 {{ Number(row.purityCoefficient || 0).toFixed(4) }} + 加价 {{ money(row.markup) }} = 卖价 {{ money(preview(row, false)) }}；减回收扣减 {{ money(row.recycleDeduction) }} = 回收价 {{ money(preview(row, true)) }}</div><div class="meta">行情：{{ row.source || '—' }} · {{ row.quoteTime || '—' }} · {{ row.marketMessage || (row.marketStatus === 'CLOSED' ? '休市' : '') }}</div><div class="actions"><button class="primary" :disabled="saving === row.type_id" @click="save(row)">{{ saving === row.type_id ? '保存中…' : '保存配置' }}</button><button v-if="row.autoFrozen || row.marketStatus === 'FROZEN'" class="outline" @click="resume(row)">恢复自动定价</button></div></article><div v-if="!types.length" class="empty">暂无可配置金类</div><section class="panel logs"><h3>最近价格变更</h3><div v-for="log in logs" :key="log.log_id" class="log-row"><span>{{ log.price_type }} · {{ log.create_time }}</span><small>卖价 {{ money(log.old_sale_price) }} → {{ money(log.new_sale_price) }}；回收 {{ money(log.old_recycle_price) }} → {{ money(log.new_recycle_price) }} · {{ log.source || '—' }}</small></div><div v-if="!logs.length" class="empty">暂无变更日志</div></section></template>
  </main></div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'
import { useAppStore } from '../stores/app.js'
import { api } from '../api/request.js'

const router = useRouter(); const auth = useAuthStore(); const app = useAppStore(); const types = ref([]); const logs = ref([]); const loading = ref(false); const saving = ref(null)
const money = value => Number(value || 0).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
const statusText = value => ({ OPEN: '开市', CLOSED: '休市', ERROR: '行情失败', FROZEN: '已冻结' }[String(value || '').toUpperCase()] || '未知')
const statusClass = value => String(value || '').toLowerCase()
const round = (value, rule) => { const n = Number(value || 0); if (rule === 'TENTH') return Math.round(n * 10) / 10; if (rule === 'YUAN') return Math.round(n); if (rule === 'TAIL_8') return Math.floor(n) + .8; if (rule === 'TAIL_9') return Math.floor(n) + .9; return Math.round(n * 100) / 100 }
const preview = (row, recycle) => round(Number(row.basePrice || 0) * Number(row.purityCoefficient || 0) + (recycle ? -Number(row.recycleDeduction || 0) : Number(row.markup || 0)), row.roundingRule)
async function load() { loading.value = true; try { types.value = await api.goldTypesAll() || []; logs.value = await api.goldLogs({ limit: 100 }) || [] } catch (e) { alert(e?.message || '金价配置加载失败') } finally { loading.value = false } }
async function save(row) { saving.value = row.type_id; try { await api.updateGoldType(row.type_id || row.type_code, { pricingMode: row.pricingMode, baseInstrument: row.baseInstrument, purityCoefficient: Number(row.purityCoefficient), markup: Number(row.markup), recycleDeduction: Number(row.recycleDeduction), roundingRule: row.roundingRule, resumeAuto: false }); await app.loadGold(); await load(); alert('金价配置已保存') } catch (e) { alert(e?.message || '保存失败') } finally { saving.value = null } }
async function resume(row) { saving.value = row.type_id; try { await api.updateGoldType(row.type_id || row.type_code, { pricingMode: 'AUTO', resumeAuto: true }); await app.loadGold(); await load(); alert('已恢复自动定价') } catch (e) { alert(e?.message || '恢复失败') } finally { saving.value = null } }
onMounted(load)
</script>

<style scoped>
.setting-card{margin-top:12px}.setting-head,.quote-line,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}.setting-head h3{margin:0 0 4px}.setting-head small,.meta{color:var(--ink-3);font-size:12px}.status{padding:3px 8px;border-radius:999px;background:#eef1f4;color:var(--ink-2);font-size:12px}.status.open{background:#e7f6ed;color:#217a42}.status.error,.status.frozen{background:#fff0e8;color:#a64b22}.quote-line{margin:14px 0;padding:10px;background:var(--gold-soft);border-radius:8px}.quote-line b{display:block;color:var(--gold-deep);font-size:17px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form-grid label{font-size:12px;color:var(--ink-2)}.form-grid input,.form-grid select{display:block;width:100%;min-height:42px;margin-top:4px;border:1px solid var(--line);border-radius:8px;padding:0 9px;background:#fff}.formula{margin-top:12px;padding:9px;background:#f7f9fc;color:var(--ink-2);font-size:12px;line-height:1.5}.meta{margin-top:8px}.actions{justify-content:flex-start;margin-top:12px}.logs{margin-top:16px}.logs h3{margin:0 0 8px}.log-row{padding:9px 0;border-top:1px solid var(--line-soft);display:grid;gap:3px;font-size:12px}.log-row small{color:var(--ink-3)}.empty{padding:24px;text-align:center;color:var(--ink-3)}
@media(max-width:520px){.form-grid{grid-template-columns:1fr}.quote-line{align-items:flex-start;flex-direction:column}}
</style>
