<template>
  <div class="shell report-shell">
    <header class="topbar"><div><strong>经营报表</strong><span class="store">{{ auth.user?.store_name || auth.user?.storeName || '默认门店' }}</span></div><div class="top-actions"><span class="online-dot" :class="{offline: app.offline}"></span><span>{{ app.offline ? '离线' : '在线' }}</span></div></header>
    <main class="content"><section class="page report-page">
      <div class="report-tabs"><button v-for="tab in tabs" :key="tab.key" :class="{active: activeTab===tab.key}" @click="go(tab.key)">{{ tab.label }}</button></div>
      <div class="report-filters">
        <div class="filter-tabs"><button v-for="item in periods" :key="item.key" :class="{active: timeType===item.key}" @click="changePeriod(item.key)">{{ item.label }}</button></div>
        <div v-if="timeType==='custom'" class="custom-range"><label><span>开始日期</span><input v-model="startDate" type="date" aria-label="开始日期" @change="load"/></label><span class="range-separator">至</span><label><span>结束日期</span><input v-model="endDate" type="date" aria-label="结束日期" @change="load"/></label></div>
        <select v-if="isManager" v-model="employeeId" @change="load"><option value="">全部员工</option><option v-for="e in employees" :key="e.user_id" :value="e.user_id">{{ e.name || e.employee_name }}</option></select>
        <select v-if="activeTab==='sales'" v-model="category" @change="load"><option value="">全部品类</option><option v-for="c in categories" :key="c.category" :value="c.category">{{ c.category }}</option></select>
      </div>
      <p v-if="error" class="report-error">{{ error }} <button class="outline" @click="load">重试</button></p>
      <div v-if="loading" class="report-loading">正在加载报表...</div>

      <template v-else-if="activeTab==='overview'">
        <div v-if="isManager" class="target-row"><label>本月销售目标（元）<input v-model.number="targetInput" type="number" min="0" step="100" :placeholder="targetValue>0?String(targetValue):'未设置'"/></label><button class="outline" @click="saveTarget">保存目标</button><small v-if="targetValue>0">当前目标 {{ money(targetValue) }}</small></div>
        <div class="kpi-grid report-kpis"><Kpi label="营业额(含加工)" :value="money(summary.turnover ?? summary.sales_amount)"/><Kpi label="毛利" :value="money(summary.gross_profit)"/><Kpi label="成交件数" :value="`${num(summary.item_count)} 件`"/><Kpi label="销售克重" :value="`${weight(summary.gold_weight)}g`"/></div>
        <Panel title="销售趋势"><div v-if="trend.length" class="report-bars"><div v-for="row in trend" :key="row.day" class="report-bar-col"><span>{{ moneyShort(row.amount) }}</span><i :style="{height: `${barHeight(row.amount, trend)}%`}"></i><small>{{ day(row.day) }}</small></div></div><div v-else class="empty">暂无销售趋势</div></Panel>
        <Panel title="品类销售"><div v-if="categoryRows.length" class="report-category-list"><div v-for="row in categoryRows" :key="row.category" class="report-list-row"><span>{{ row.category }}</span><strong>{{ money(row.amount) }}</strong><small>{{ num(row.item_count) }} 件 · {{ weight(row.weight) }}g</small></div></div><div v-else class="empty">暂无品类数据</div></Panel>
        <Panel v-if="isManager" title="员工销售排行"><div v-if="employeeRows.length" class="report-category-list"><button v-for="(row,index) in employeeRows" :key="row.user_id || index" class="report-list-row report-row-button" @click="openEmployeeDetail(row)"><span><b class="rank-no">{{ index+1 }}</b> {{ row.name || row.employee_name || '员工' }}<small class="report-row-sub">{{ num(row.order_count) }} 单 · 提成 {{ money(row.commission) }}</small></span><strong>{{ money(row.amount ?? row.sales_amount) }}</strong><span class="report-row-action">查看 ›</span></button></div><div v-else class="empty">暂无员工销售数据</div></Panel>
        <Panel title="销售明细"><div v-if="records.length" class="report-category-list"><button v-for="row in records" :key="row.order_id + '-' + row.goods_name" class="report-list-row report-row-button" @click="openSalesDetail(row)"><span>{{ row.goods_name || '商品' }}<small class="report-row-sub">{{ row.order_no || row.order_id || '-' }} · {{ row.date || '-' }}</small></span><strong>{{ money(row.amount) }}</strong><span class="report-row-action">查看 ›</span></button></div><div v-else class="empty">暂无销售明细</div></Panel>
      </template>

      <template v-else-if="activeTab==='sales'">
        <div class="kpi-grid report-kpis"><Kpi label="销售金额" :value="money(salesSummary.sales_amount)"/><Kpi label="销售克重" :value="`${weight(salesSummary.gold_weight)}g`"/><Kpi label="销售件数" :value="`${num(salesSummary.item_count)} 件`"/><Kpi label="客单价" :value="money(salesSummary.avg_order)"/></div>
        <Panel title="品类占比"><div class="report-category-list"><div v-for="row in categoryRows" :key="row.category" class="report-list-row"><span>{{ row.category }}</span><strong>{{ percent(row.amount, salesSummary.sales_amount) }}</strong><small>{{ money(row.amount) }} · {{ num(row.item_count) }} 件</small></div><div v-if="!categoryRows.length" class="empty">暂无品类数据</div></div></Panel>
        <Panel title="销售明细"><button v-for="row in salesRecords" :key="row.order_id + '-' + row.goods_name" class="report-list-row report-row-button" @click="openSalesDetail(row)"><span>{{ row.goods_name || '商品' }}<small class="report-row-sub">{{ row.order_no || row.order_id || '-' }} · {{ row.date || '-' }}</small></span><strong>{{ money(row.amount) }}</strong><span class="report-row-action">查看 ›</span></button><div v-if="!salesRecords.length" class="empty">暂无销售明细</div></Panel>
      </template>

      <template v-else-if="activeTab==='employee'">
        <div class="kpi-grid report-kpis"><Kpi label="员工人数" :value="`${employeeRows.length} 人`"/><Kpi label="人均业绩" :value="money(employeeAverage)"/><Kpi label="业绩冠军" :value="employeeRows[0]?.name || '-'"/><Kpi label="冠军金额" :value="money(employeeRows[0]?.sales_amount)"/></div>
        <Panel title="员工排行"><div class="report-bars employee-bars"><div v-for="(row,index) in employeeRows" :key="row.user_id || index" class="report-bar-col"><span>{{ moneyShort(row.sales_amount) }}</span><i :class="`rank-${index+1}`" :style="{height: `${barHeight(row.sales_amount, employeeRows, 'sales_amount')}%`}"></i><small>{{ row.name }}</small></div></div><div v-if="!employeeRows.length" class="empty">暂无员工数据</div></Panel>
        <Panel title="员工明细"><button v-for="row in employeeRows" :key="row.user_id" class="report-list-row report-row-button" @click="openEmployeeDetail(row)"><span>{{ row.name || row.employee_name || '员工' }}<small class="report-row-sub">{{ num(row.order_count) }} 单 · {{ weight(row.weight) }}g</small></span><strong>{{ money(row.sales_amount ?? row.amount) }}</strong><span class="report-row-action">查看 ›</span></button><div v-if="!employeeRows.length" class="empty">暂无员工数据</div></Panel>
      </template>

      <template v-else-if="activeTab==='recycle'"><div class="kpi-grid report-kpis"><Kpi label="回收总额" :value="money(recycle.amount)"/><Kpi label="回收克重" :value="`${weight(recycle.weight)}g`"/><Kpi label="回收单数" :value="`${num(recycle.order_count)} 单`"/><Kpi label="折旧损耗" :value="money(recycle.deduct_loss)"/></div><div class="kpi-grid report-kpis"><Kpi label="以旧换新" :value="`${num(recycle.trade_in_count)} 单`"/><Kpi label="换新差价" :value="money(recycle.trade_in_amount)"/></div><Panel title="回收趋势"><div v-if="recycle.trend?.length" class="report-bars"><div v-for="row in recycle.trend" :key="row.day" class="report-bar-col"><span>{{ weight(row.weight) }}g</span><i :style="{height: `${barHeight(row.weight,recycle.trend,'weight')}%`}"></i><small>{{ day(row.day) }}</small></div></div><div v-else class="empty">暂无回收趋势</div></Panel><Panel title="回收明细"><div v-for="row in recycle.records || []" :key="row.recycle_order_id" class="report-list-row"><span>{{ row.material_type || '旧料' }}<small>{{ row.bill_no }} · {{ row.create_time }}</small></span><strong>{{ money(row.total_amount) }}</strong><small>{{ weight(row.weight) }}g · {{ percent(row.purity,1) }}</small></div><div v-if="!recycle.records?.length" class="empty">暂无回收数据</div></Panel><Panel title="以旧换新明细（报价记录）"><div v-for="row in recycle.trade_in_records || []" :key="row.trade_in_id" class="report-list-row"><span>换新 {{ row.bill_no }}<small>{{ row.create_time }} · {{ tradeInStatus(row.status) }}</small></span><strong>{{ money(row.diff_amount) }}</strong><small>{{ oldNewText(row) }}</small></div><div v-if="!recycle.trade_in_records?.length" class="empty">暂无换新记录</div></Panel></template>
      <template v-else-if="activeTab==='member'"><div class="kpi-grid report-kpis"><Kpi label="新增会员" :value="`${num(member.new_members)} 人`"/><Kpi label="会员总数" :value="`${num(member.total_members)} 人`"/><Kpi label="会员消费额" :value="money(member.consume_amount)"/><Kpi label="消费占比" :value="percent(member.consume_amount, summary.sales_amount)"/></div><Panel title="会员明细"><div v-for="row in member.records || []" :key="row.member_id" class="report-list-row"><span>{{ row.name }}<small>{{ row.phone || '-' }} · {{ row.gender || '未填写' }}</small></span><strong>{{ money(row.total_consume) }}</strong><small>{{ row.create_time?.slice(0,10) }}</small></div><div v-if="!member.records?.length" class="empty">暂无会员数据</div></Panel></template>
      <template v-else><div class="kpi-grid report-kpis"><Kpi label="周期均价" :value="money(goldAverage)"/><Kpi label="最高价" :value="money(goldMax)"/><Kpi label="最低价" :value="money(goldMin)"/><Kpi label="波动幅度" :value="percent(goldMax-goldMin,goldAverage)"/></div><Panel title="金价走势"><GoldTrend :points="gold.prices || []"/></Panel><Panel title="销售克重"><div v-for="row in gold.salesWeight || []" :key="row.day" class="report-list-row"><span>{{ day(row.day) }}</span><strong>{{ weight(row.weight) }}g</strong></div><div v-if="!gold.salesWeight?.length" class="empty">暂无销售克重数据</div></Panel><Panel title="金价区间销售分布"><div v-for="row in gold.distribution || []" :key="row.price_bucket" class="report-list-row"><span>{{ priceBucket(row.price_bucket) }}</span><strong>{{ weight(row.weight) }}g</strong><small>该金价区间销售克重</small></div><div v-if="!gold.distribution?.length" class="empty">暂无金价区间销售数据</div></Panel></template>
    </section></main>
    <div v-if="detailDrawer.open" class="detail-drawer-mask" @click.self="closeDetailDrawer">
      <section class="detail-drawer" role="dialog" aria-modal="true" :aria-label="detailDrawer.type === 'employee' ? '员工销售明细' : '销售明细详情'">
        <header class="detail-drawer-head"><strong>{{ detailDrawer.type === 'employee' ? '员工销售明细' : '销售明细详情' }}</strong><button class="modal-close" aria-label="关闭详情" @click="closeDetailDrawer">×</button></header>
        <div class="detail-drawer-body">
          <div v-if="drawerLoading" class="empty">加载明细中...</div>
          <template v-else-if="detailDrawer.type === 'employee' && detailDrawer.employee">
            <div class="detail-drawer-title"><b>{{ detailDrawer.employee.name || detailDrawer.employee.employee_name || '员工' }}</b><small>所选周期</small></div>
            <div class="kpi-grid report-kpis"><Kpi label="销售额" :value="money(detailDrawer.employee.amount ?? detailDrawer.employee.sales_amount)"/><Kpi label="订单数" :value="`${num(detailDrawer.employee.order_count)} 单`"/><Kpi label="销售克重" :value="`${weight(detailDrawer.employee.weight)}g`"/><Kpi label="提成" :value="money(detailDrawer.employee.commission)"/></div>
            <div class="detail-drawer-facts"><div><span>回收业绩</span><b>{{ money(detailDrawer.employee.recycle_amount) }}</b></div><div><span>开发会员</span><b>{{ num(detailDrawer.employee.member_count) }} 人</b></div></div>
            <h3 class="detail-drawer-section">品类明细</h3><div v-for="row in detailDrawer.employee.categories || []" :key="row.category" class="report-list-row"><span>{{ row.category || '未分类' }}</span><strong>{{ money(row.amount) }}</strong><small>{{ num(row.item_count) }} 件 · {{ weight(row.weight) }}g</small></div><div v-if="!detailDrawer.employee.categories?.length" class="empty">暂无品类明细</div>
          </template>
          <template v-else-if="detailDrawer.sale">
            <div class="detail-drawer-title"><b>{{ detailDrawer.sale.goods_name || '商品' }}</b><small>{{ detailDrawer.sale.order_no || detailDrawer.sale.order_id || '无订单号' }}</small></div>
            <div class="detail-drawer-facts"><div><span>成交金额</span><b>{{ money(detailDrawer.sale.amount) }}</b></div><div><span>销售数量</span><b>{{ num(detailDrawer.sale.quantity || 1) }} 件</b></div><div><span>销售克重</span><b>{{ weight(detailDrawer.sale.weight) }}g</b></div><div><span>品类</span><b>{{ detailDrawer.sale.category || '未分类' }}</b></div><div><span>成交日期</span><b>{{ detailDrawer.sale.date || '-' }}</b></div><div><span>销售员工</span><b>{{ detailDrawer.sale.employee_name || detailDrawer.sale.employeeName || '-' }}</b></div></div>
          </template>
        </div>
      </section>
    </div>
    <nav class="tabbar"><button @click="router.push(isManager ? '/manager/dashboard' : '/sales/home')"><span>⌂</span>首页</button><button class="active"><span>↗</span>报表</button><button @click="router.push(isManager ? '/manager/member' : '/sales/members')"><span>👤</span>会员</button><button @click="router.push('/notifications')"><span>●</span>消息</button><button @click="router.push(isManager ? '/manager/profile' : '/sales/profile')"><span>⚙</span>我的</button></nav>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'
import { useAppStore } from '../stores/app.js'
import { api } from '../api/request.js'
import Kpi from '../components/Kpi.vue'
import Panel from '../components/Panel.vue'
import GoldTrend from '../components/GoldTrend.vue'
const route=useRoute(); const router=useRouter(); const auth=useAuthStore(); const app=useAppStore(); const isManager=computed(()=>['ADMIN','MANAGER'].includes(auth.role));
const tabs=[{key:'overview',label:'概览'},{key:'sales',label:'销售明细'},{key:'employee',label:'员工/个人'},{key:'recycle',label:'回收换新'},{key:'member',label:'会员分析'},{key:'gold',label:'金价关联'}]; const periods=[{key:'today',label:'今天'},{key:'yesterday',label:'昨天'},{key:'week',label:'本周'},{key:'month',label:'本月'},{key:'lastMonth',label:'上月'},{key:'custom',label:'自定义'}];
const activeTab=computed(()=>['sales','employee','recycle','member','gold'].includes(String(route.params.kind))?String(route.params.kind):'overview'); const timeType=ref('month'); const startDate=ref(''); const endDate=ref(''); const employeeId=ref(''); const category=ref(''); const loading=ref(false); const error=ref(''); const overview=ref({summary:{},trend:[],categories:[],employees:[],records:[]}); const sales=ref({summary:{},records:[]}); const employee=ref({employees:[]}); const recycle=ref({}); const member=ref({}); const gold=ref({prices:[],salesWeight:[]}); const targetValue=ref(0); const targetInput=ref(0); const drawerLoading=ref(false); const detailDrawer=ref({open:false,type:'',employee:null,sale:null})
const summary=computed(()=>overview.value.summary||{}); const trend=computed(()=>overview.value.trend||[]); const categoryRows=computed(()=>overview.value.categories||[]); const records=computed(()=>overview.value.records||[]); const employees=computed(()=>overview.value.employees||[]); const employeeRows=computed(()=>employee.value.employees?.length?employee.value.employees:employees.value); const salesSummary=computed(()=>sales.value.summary?.summary||sales.value.summary||summary.value); const salesRecords=computed(()=>sales.value.records||[]); const categories=computed(()=>categoryRows.value); const employeeAverage=computed(()=>employeeRows.value.length?employeeRows.value.reduce((s,r)=>s+Number(r.sales_amount||r.amount||0),0)/employeeRows.value.length:0); const goldValues=computed(()=> (gold.value.prices||[]).map(x=>Number(x.price||0)).filter(Boolean)); const goldAverage=computed(()=>Number(gold.value.average ?? (goldValues.value.length?goldValues.value.reduce((s,x)=>s+x,0)/goldValues.value.length:0))); const goldMax=computed(()=>Number(gold.value.max ?? Math.max(0,...goldValues.value))); const goldMin=computed(()=>Number(gold.value.min ?? (goldValues.value.length?Math.min(...goldValues.value):0)))
const num=v=>Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:0}); const tradeInStatus=v=>({1:'已成交',2:'待审批',4:'已驳回'}[Number(v)]||'-')
const oldNewText=row=>{const text=v=>{try{const o=typeof v==='string'?JSON.parse(v):v;if(o&&typeof o==='object')return Object.values(o).filter(Boolean).join(' / ')||'-';return String(v||'-')}catch{return String(v||'-')}};return `旧:${text(row.old_material_info)} → 新:${text(row.new_goods_info)}`}
const money=v=>`¥${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`; const moneyShort=v=>{const n=Number(v||0);return n>=10000?`¥${(n/10000).toFixed(1)}万`:`¥${Math.round(n)}`}; const weight=v=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:3}); const percent=(a,b)=>`${b?((Number(a||0)/Number(b||1))*100).toFixed(1):'0.0'}%`; const day=v=>String(v||'').slice(5,10)||'-'; const barHeight=(value,rows,key='amount')=>{const max=Math.max(...rows.map(r=>Number(r[key] != null ? r[key] : (r.amount || 0))),1);return Math.max(6,Number(value||0)/max*100)}
const priceBucket=v=>`¥${Number(v||0).toLocaleString('zh-CN',{maximumFractionDigits:0})} - ¥${(Number(v||0)+10).toLocaleString('zh-CN',{maximumFractionDigits:0})}`
function go(key){router.push(key==='overview'?'/report':`/report/${key}`)} function setDefaultCustomRange(){const now=new Date();const pad=value=>String(value).padStart(2,'0');if(!startDate.value)startDate.value=`${now.getFullYear()}-${pad(now.getMonth()+1)}-01`;if(!endDate.value)endDate.value=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`} function changePeriod(v){timeType.value=v;if(v==='custom')setDefaultCustomRange();load()} function closeDetailDrawer(){detailDrawer.value={open:false,type:'',employee:null,sale:null};drawerLoading.value=false} async function openEmployeeDetail(row){detailDrawer.value={open:true,type:'employee',employee:row,sale:null};if(!row.categories&&row.user_id){drawerLoading.value=true;try{const d=await api.reportEmployee({timeType:timeType.value,employeeId:row.user_id});const detail=(d?.employees||[])[0];if(detail){Object.assign(row,detail);detailDrawer.value={...detailDrawer.value,employee:row}}}catch{}finally{drawerLoading.value=false}}} function openSalesDetail(row){detailDrawer.value={open:true,type:'sale',employee:null,sale:row}}
async function load(){loading.value=true;error.value='';try{const params={timeType:timeType.value}; if(timeType.value==='custom'){if(startDate.value)params.startDate=startDate.value;if(endDate.value)params.endDate=endDate.value} if(employeeId.value)params.employeeId=employeeId.value; if(category.value)params.category=category.value; if(activeTab.value==='overview'){overview.value=await api.reportOverview(params)||{}} else if(activeTab.value==='sales'){const [salesData,overviewData]=await Promise.all([api.reportSales(params),api.reportOverview(params)]); sales.value=salesData||{}; overview.value=overviewData||{}} else if(activeTab.value==='employee'){employee.value=await api.reportEmployee(params)||{}} else if(activeTab.value==='recycle'){recycle.value=await api.reportRecycle(params)||{}} else if(activeTab.value==='member'){member.value=await api.reportMember(params)||{}} else {gold.value=await api.reportGold(params)||{}}}catch(e){error.value=e?.message||'报表加载失败'}finally{loading.value=false}}
async function loadTarget(){if(!isManager.value)return;try{const t=await api.systemTarget();targetValue.value=Number(t?.monthlySalesTarget||0);targetInput.value=targetValue.value}catch{}}
async function saveTarget(){const v=Number(targetInput.value||0);if(v<0)return alert('目标金额不能为负');try{await api.setTarget(v);targetValue.value=v;alert('本月销售目标已保存')}catch(e){alert(e?.message||'目标保存失败')}}
onMounted(()=>{load();loadTarget()})
watch(activeTab,()=>{closeDetailDrawer();load()})
watch(()=>app.eventVersion,()=>{if(['REPORT_UPDATED','COMMISSION_UPDATED','TARGET_UPDATED','ORDER_COMPLETED','RECYCLE_COMPLETED','TRADE_IN_UPDATED','PROCESSING_ORDER_UPDATED'].includes(app.lastEventType)){load();if(app.lastEventType==='TARGET_UPDATED')loadTarget()}})
</script>
