package com.dajin.system.goods;
import com.dajin.system.common.*; import com.dajin.system.config.RequirePermission; import com.dajin.system.config.SyncWebSocketHandler; import org.springframework.jdbc.core.namedparam.*; import org.springframework.web.bind.annotation.*; import javax.servlet.http.*; import javax.validation.Valid; import javax.validation.constraints.*; import java.math.*; import java.util.*;
@RestController @RequestMapping("/api/goods") @RequirePermission("goods:search") public class GoodsController {
 private final DbSupport db; private final SyncWebSocketHandler ws; public GoodsController(DbSupport db,SyncWebSocketHandler ws){this.db=db;this.ws=ws;}
  @GetMapping("/list") public ApiResponse<?> list(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String keyword,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)Long parentCategoryId,@RequestParam(required=false)Integer priceType,@RequestParam(required=false)Integer status,@RequestParam(defaultValue="false")boolean includeInactive,HttpServletRequest r){int off=(page-1)*size; String k=keyword==null?"":keyword; MapSqlParameterSource p=new MapSqlParameterSource().addValue("s",db.store(r)).addValue("k","%"+k+"%").addValue("cat",categoryId).addValue("parentCat",parentCategoryId).addValue("pt",priceType).addValue("st",status).addValue("all",includeInactive?1:0).addValue("limit",size).addValue("off",off); String where="g.store_id=:s and (g.name like :k or g.barcode like :k) and (:cat is null or g.category_id=:cat) and (:parentCat is null or c.parent_id=:parentCat) and (:pt is null or g.price_type=:pt) and (:all=1 or (g.status=1 and greatest(g.stock-coalesce(rs.reserved_stock,0),0)>0)) and (:st is null or g.status=:st)"; String from="goods g left join goods_category c on c.category_id=g.category_id and c.store_id=g.store_id left join goods_category pc on pc.category_id=c.parent_id and pc.store_id=c.store_id left join (select goods_id,min(piece_id) mp from goods_piece where store_id=:s and status=1 group by goods_id) fp on fp.goods_id=g.goods_id left join goods_piece fpp on fpp.piece_id=fp.mp left join (select soi.store_id,soi.goods_id,sum(soi.qty) reserved_stock from sales_order_item soi join sales_order so on so.order_id=soi.order_id and so.store_id=soi.store_id where soi.store_id=:s and so.status in (0,3) group by soi.store_id,soi.goods_id) rs on rs.store_id=g.store_id and rs.goods_id=g.goods_id"; return ApiResponse.ok(Map.of("records",db.list("select g.*,greatest(g.stock-coalesce(rs.reserved_stock,0),0) available_stock,coalesce(rs.reserved_stock,0) reserved_stock,c.name category,c.parent_id parent_category_id,pc.name parent_category,c.category_code category_code,fpp.image piece_image from "+from+" where "+where+" order by g.goods_id desc limit :limit offset :off",p),"total",db.jdbc().queryForObject("select count(*) from "+from+" where "+where,p,Integer.class)));}
  @GetMapping("/scan/{barcode}") public ApiResponse<?> scan(@PathVariable String barcode,HttpServletRequest r){List<Map<String,Object>> x=db.list("select g.*,greatest(g.stock-coalesce(rs.reserved_stock,0),0) available_stock,c.name category from goods g left join goods_category c on c.category_id=g.category_id and c.store_id=g.store_id left join (select soi.store_id,soi.goods_id,sum(soi.qty) reserved_stock from sales_order_item soi join sales_order so on so.order_id=soi.order_id and so.store_id=soi.store_id where soi.store_id=:s and so.status in (0,3) group by soi.store_id,soi.goods_id) rs on rs.store_id=g.store_id and rs.goods_id=g.goods_id where g.store_id=:s and g.barcode=:b and g.status=1 and greatest(g.stock-coalesce(rs.reserved_stock,0),0)>0 limit 1",Map.of("s",db.store(r),"b",barcode)); if(x.isEmpty())throw new BusinessException(404001,"商品不存在、未上架，或已被待收款订单占用"); return ApiResponse.ok(x.get(0));}
 @GetMapping("/categories") public ApiResponse<?> categories(HttpServletRequest r){long store=db.store(r); return ApiResponse.ok(db.list("select c.category_id,c.name,c.category_code,c.parent_id,c.level,c.sort from goods_category c where c.store_id=:s and c.status=1 order by c.level,c.parent_id,c.sort,c.category_id",Map.of("s",store)));}
 public record GoodsReq(@NotBlank String barcode,@NotBlank String name,Long categoryId,@DecimalMin(value="0.001", inclusive=true) BigDecimal weight,@NotNull(message="成本价必填") @DecimalMin(value="0", inclusive=true) BigDecimal costPrice,@NotNull(message="售价必填") @DecimalMin(value="0", inclusive=true) BigDecimal salePrice,@NotNull Integer priceType,String goldType,@PositiveOrZero Integer stock,String images,String certificateNo){}
  @PostMapping @RequirePermission("goods:manage") public ApiResponse<?> create(@Valid @RequestBody GoodsReq q,HttpServletRequest r){
  long store=db.store(r); Long category=q.categoryId();
  if(category==null){List<Map<String,Object>> defaults=db.list("select category_id from goods_category where store_id=:s and level=2 and status=1 order by category_id limit 1",Map.of("s",store));if(defaults.isEmpty())throw new BusinessException(400106,"请先创建启用的二级商品分类");category=((Number)defaults.get(0).get("category_id")).longValue();}
  ensureCategory(store,category); ensureGoldType(store,q.priceType(),q.goldType());
   MapSqlParameterSource p=new MapSqlParameterSource().addValue("s",store).addValue("barcode",q.barcode()).addValue("name",q.name()).addValue("category",category).addValue("weight",q.weight()).addValue("cost",q.costPrice()).addValue("sale",q.salePrice()).addValue("type",q.priceType()).addValue("goldType",q.goldType()==null?"足金":q.goldType()).addValue("stock",q.stock()==null?0:q.stock()).addValue("images",q.images()).addValue("certificateNo",q.certificateNo());
   // A newly created goods master is inventory-only until an operator explicitly
   // lists it for sale. This keeps 商品 (sellable subset) downstream of 库存.
   db.jdbc().update("insert into goods(store_id,barcode,name,category_id,weight,cost_price,sale_price,price_type,gold_type,certificate_no,stock,images,status,create_time,update_time) values(:s,:barcode,:name,:category,:weight,:cost,:sale,:type,:goldType,:certificateNo,:stock,:images,0,now(),now())",p); broadcast(store,null,"CREATE"); return ApiResponse.ok();}
 @PutMapping("/{id}") @RequirePermission("goods:manage") public ApiResponse<?> update(@PathVariable long id,@Valid @RequestBody GoodsReq q,HttpServletRequest r){long store=db.store(r);if(q.categoryId()!=null)ensureCategory(store,q.categoryId());ensureGoldType(store,q.priceType(),q.goldType());MapSqlParameterSource p=new MapSqlParameterSource().addValue("id",id).addValue("s",store).addValue("name",q.name()).addValue("category",q.categoryId()).addValue("sale",q.salePrice()).addValue("cost",q.costPrice()).addValue("priceType",q.priceType()).addValue("goldType",q.goldType()).addValue("certificateNo",q.certificateNo()).addValue("weight",q.weight()).addValue("images",q.images()); int changed=db.jdbc().update("update goods set name=:name,category_id=coalesce(:category,category_id),sale_price=:sale,cost_price=:cost,price_type=:priceType,gold_type=coalesce(:goldType,gold_type),certificate_no=:certificateNo,weight=:weight,images=:images,update_time=now(),version=version+1 where goods_id=:id and store_id=:s",p);if(changed==0)throw new BusinessException(404111,"库存货品不存在");broadcast(store,id,"UPDATE");return ApiResponse.ok();}
  @PatchMapping("/{id}/status") @RequirePermission("goods:manage") public ApiResponse<?> status(@PathVariable long id,@RequestParam int status,HttpServletRequest r){
   if(status!=0&&status!=1) throw new BusinessException(400111,"销售状态不合法");
   long store=db.store(r);
   if(status==1){
    BigDecimal stock=db.jdbc().queryForObject("select coalesce(stock,0) from goods where goods_id=:id and store_id=:s",new MapSqlParameterSource().addValue("id",id).addValue("s",store),BigDecimal.class);
    if(stock==null) throw new BusinessException(404111,"库存货品不存在");
    if(stock.signum()<=0) throw new BusinessException(409111,"库存数量为0，入库后才能上架销售");
   }
   int changed=db.jdbc().update("update goods set status=:st,update_time=now(),version=version+1 where goods_id=:id and store_id=:s",new MapSqlParameterSource().addValue("id",id).addValue("s",store).addValue("st",status));
   if(changed==0) throw new BusinessException(404111,"库存货品不存在");
   broadcast(store,id,"STATUS");
   return ApiResponse.ok(Map.of("status",status));
  }
 @PatchMapping("/{id}/images") @RequirePermission("goods:manage") public ApiResponse<?> updateImages(@PathVariable long id,@RequestBody Map<String,Object> body,HttpServletRequest r){Object v=body.get("images"); if(!(v instanceof List<?> list)||list.isEmpty()||list.size()>9||list.stream().anyMatch(x->!(x instanceof String s)||s.isBlank()))throw new BusinessException(400110,"图片参数不合法"); String json; try{json=new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(list);}catch(Exception e){throw new BusinessException(400110,"图片参数不合法");}long store=db.store(r);int changed=db.jdbc().update("update goods set images=:imgs,update_time=now(),version=version+1 where goods_id=:id and store_id=:s",new MapSqlParameterSource().addValue("id",id).addValue("imgs",json).addValue("s",store));if(changed==0)throw new BusinessException(404111,"库存货品不存在");broadcast(store,id,"IMAGES");return ApiResponse.ok();}
 private void broadcast(long store,Long goodsId,String action){Map<String,Object> event=new LinkedHashMap<>();event.put("storeId",store);event.put("goodsId",goodsId);event.put("action",action);ws.broadcast("GOODS_UPDATED",event);}
 private void ensureCategory(long store,long category){int count=db.jdbc().queryForObject("select count(*) from goods_category where store_id=:s and category_id=:c and level=2 and status=1",Map.of("s",store,"c",category),Integer.class);if(count==0)throw new BusinessException(400107,"商品必须选择启用的二级分类");}
 private void ensureGoldType(long store,Integer priceType,String goldType){if(priceType==null||priceType!=1)return;String type=goldType==null?"足金":goldType.trim();if(type.isBlank())throw new BusinessException(400108,"按克商品必须选择贵金属类型");try{String json=String.valueOf(db.one("select config_value from sys_config where store_id=:s and config_key='gold_metal_types' and enabled=1",Map.of("s",store)).get("config_value"));com.fasterxml.jackson.databind.JsonNode values=new com.fasterxml.jackson.databind.ObjectMapper().readTree(json);for(com.fasterxml.jackson.databind.JsonNode value:values)if(value.path("status").asInt(1)==1&&(type.equals(value.path("name").asText())||type.equals(value.path("code").asText())))return;}catch(Exception ignored){}throw new BusinessException(400109,"贵金属类型不存在或已禁用");}
}
