<script setup>
import { onMounted, onBeforeUnmount, ref, nextTick, watch } from 'vue'
import * as echarts from 'echarts/core'
import { LineChart } from 'echarts/charts'; import { GridComponent, TooltipComponent, LegendComponent } from 'echarts/components'; import { CanvasRenderer } from 'echarts/renderers'
import { dashboardApi } from '../api/modules'
import { useAppStore } from '../stores/app'
import { useAuthStore } from '../stores/auth'
echarts.use([LineChart,GridComponent,TooltipComponent,LegendComponent,CanvasRenderer])
const auth=useAuthStore(); const app=useAppStore();const data=ref({revenue:0,orderCount:0,weight:0,grossMargin:0,pendingApproval:0,stockWarnings:0,trend:[],ranking:[]});const chart=ref();const loading=ref(false);const error=ref('');let chartInstance
let disposed = false
async function load(){if(loading.value)return;chartInstance?.dispose();chartInstance=null;loading.value=true;error.value='';try{const result=await dashboardApi.get();if(disposed)return;data.value={...result,trend:result.trend||[],ranking:result.ranking||[]}}catch(e){error.value=e?.message||'仪表盘加载失败'}finally{loading.value=false}await nextTick();if(disposed||error.value||!chart.value)return;chartInstance=echarts.init(chart.value);chartInstance.setOption({tooltip:{trigger:'axis'},grid:{left:45,right:20,top:18,bottom:28},xAxis:{type:'category',data:data.value.trend.map(x=>x.day)},yAxis:{type:'value'},series:[{name:'营业额',type:'line',smooth:true,data:data.value.trend.map(x=>x.amount),lineStyle:{color:'#b97930'},itemStyle:{color:'#b97930'},areaStyle:{color:'rgba(185,121,48,.10)'}}]})}
const resizeChart=()=>chartInstance?.resize();onMounted(()=>{load();window.addEventListener('resize',resizeChart)});onBeforeUnmount(()=>{disposed=true;chartInstance?.dispose();window.removeEventListener('resize',resizeChart)});watch(()=>app.eventVersion,load)
const money=v=>`¥${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2})}`
</script>
<template><el-alert v-if="error" :title="error" type="error" show-icon/><el-skeleton v-if="loading" :rows="4" animated/><template v-else-if="!error"><div v-if="auth.can('report:store-performance')" class="kpi-grid"><div class="panel kpi"><div class="kpi-label">今日营业额</div><div class="kpi-value">{{money(data.revenue)}}</div><div class="kpi-note">已结算 · 含加工费{{Number(data.processingRevenue||0)?` ¥${Number(data.processingRevenue).toFixed(2)}`:''}}</div></div><div class="panel kpi"><div class="kpi-label">销售克重</div><div class="kpi-value">{{Number(data.weight||0).toFixed(3)}}g</div><div class="kpi-note">今日成交</div></div><div class="panel kpi"><div class="kpi-label">订单数</div><div class="kpi-value">{{data.orderCount||0}}</div><div class="kpi-note">已完成订单</div></div><div class="panel kpi"><div class="kpi-label">毛利率</div><div class="kpi-value">{{(Number(data.grossMargin||0)*100).toFixed(1)}}%</div><div class="kpi-note">按商品成本估算</div></div></div><div class="grid-2"><section v-if="auth.can('report:store-performance') && data.trend.length" class="panel"><div class="panel-title">7日营业额趋势</div><div class="chart" ref="chart"></div></section><section class="panel"><div class="panel-title">待办提醒</div><div class="notice-row" @click="$router.push('/approval')"><span>待审批单据</span><el-tag type="warning">{{data.pendingApproval||0}} 条</el-tag></div><div class="notice-row" @click="$router.push('/stock')"><span>库存预警</span><el-tag type="danger">{{data.stockWarnings||0}} 件</el-tag></div><div v-if="auth.can('report:store-performance')" class="panel-title" style="margin-top:28px">员工销售排行</div><el-table v-if="auth.can('report:store-performance')" :data="data.ranking" size="small"><el-table-column prop="name" label="员工"/><el-table-column prop="amount" label="销售额"><template #default="s">{{money(s.row.amount)}}</template></el-table-column></el-table></section></div></template><el-button v-if="error" type="primary" @click="load">重试</el-button></template>
