<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { goodsApi, goldApi, uploadApi } from '../api/modules'
import CategoryManagementDialog from '../components/CategoryManagementDialog.vue'
import { useAppStore } from '../stores/app'
const app=useAppStore()
const rows=ref([]),categories=ref([]),roots=ref([]),goldTypes=ref([]),dialog=ref(false),categoryDialog=ref(false),editing=ref(null)
const filters=reactive({keyword:'',parentCategoryId:null,categoryId:null,priceType:null,status:1})
const form=reactive({barcode:'',name:'',parentCategoryId:null,categoryId:null,weight:null,costPrice:0,salePrice:0,priceType:1,goldType:'足金',stock:0,images:'[]'})
const columns=[{key:'barcode',label:'条码'},{key:'name',label:'名称'},{key:'category',label:'分类'},{key:'gold_type',label:'贵金属类型'},{key:'weight',label:'克重'},{key:'cost_price',label:'成本价'},{key:'sale_price',label:'售价'},{key:'price_type',label:'计价方式'},{key:'stock',label:'库存'},{key:'status',label:'状态'}]
const priceText=v=>({1:'按克',2:'按件',3:'标签'})[v]||v
const parseImages=v=>{let l=v;if(typeof l==='string'){try{l=JSON.parse(l||'[]')}catch{l=[]}}return Array.isArray(l)?l.filter(Boolean):[]}
const rowImages=r=>{if(r?.piece_image)return [r.piece_image,...parseImages(r.images).filter(u=>u!==r.piece_image)];return parseImages(r?.images)}
const refreshCategoryTree=()=>{roots.value=categories.value.filter(c=>Number(c.level||(Number(c.parent_id)?2:1))===1)}
const childrenOf=p=>categories.value.filter(c=>Number(c.level)===2&&Number(c.parent_id)===Number(p)&&Number(c.status)===1)
async function load(){const d=await goodsApi.list({...filters,includeInactive:true});rows.value=d.records||[]}
async function loadCategories(){categories.value=await goodsApi.categories();refreshCategoryTree()}
async function onCategoriesChanged(rows){categories.value=rows || []; refreshCategoryTree(); await load()}
function open(row){editing.value=row||null;Object.assign(form,row?{...row,categoryId:row.category_id,parentCategoryId:row.parent_category_id,costPrice:row.cost_price,salePrice:row.sale_price,priceType:row.price_type,goldType:row.gold_type||'足金'}:{barcode:'',name:'',parentCategoryId:roots.value[0]?.category_id||null,categoryId:null,weight:null,costPrice:0,salePrice:0,priceType:1,goldType:goldTypes.value[0]?.type_name||'足金',stock:0,images:'[]'});dialog.value=true}
async function save(){if(!editing.value)return ElMessage.warning('请从库存货品中选择要编辑的记录');if(!form.barcode.trim()||!form.name.trim())return ElMessage.warning('条码和名称不能为空');if(!form.categoryId)return ElMessage.warning('请选择二级子类');if(Number(form.costPrice)<0||Number(form.salePrice)<0)return ElMessage.warning('价格不能为负数');if(Number(form.priceType)===1&&!(Number(form.weight)>0))return ElMessage.warning('按克商品的克重必须大于0');await goodsApi.update(editing.value.goods_id,form);dialog.value=false;ElMessage.success('销售属性已保存');await load()}
async function toggle(row){await goodsApi.status(row.goods_id,row.status===1?0:1);ElMessage.success('状态已更新');await load()}
async function image(e){const f=e.target.files?.[0];if(f){const d=await uploadApi.image(f);form.images=JSON.stringify([d.url]);ElMessage.success('图片已上传')}}
onMounted(async()=>{await loadCategories();goldTypes.value=await goldApi.types()||[];await load()})
watch(()=>app.eventVersion,async()=>{if(['GOODS_UPDATED','STOCK_UPDATED','STOCK_IN_COMPLETED'].includes(app.lastEventType))await load();if(app.lastEventType==='CATEGORIES_UPDATED')await loadCategories();if(app.lastEventType==='GOLD_TYPES_UPDATED')goldTypes.value=await goldApi.types()||[]})
</script>
<template>
<section class="panel"><div class="page-toolbar"><div class="filters"><el-input v-model="filters.keyword" clearable placeholder="搜索名称 / 条码" style="width:220px" @keyup.enter="load"/><el-select v-model="filters.parentCategoryId" clearable placeholder="一级分类" style="width:150px" @change="filters.categoryId=null"><el-option v-for="c in roots" :key="c.category_id" :value="c.category_id" :label="c.name"/></el-select><el-select v-model="filters.categoryId" clearable placeholder="二级子类" style="width:160px"><el-option v-for="c in categories.filter(x=>Number(x.level)===2&&(!filters.parentCategoryId||Number(x.parent_id)===Number(filters.parentCategoryId)))" :key="c.category_id" :value="c.category_id" :label="c.name"/></el-select><el-select v-model="filters.priceType" clearable placeholder="计价方式" style="width:130px"><el-option :value="1" label="按克"/><el-option :value="2" label="按件"/><el-option :value="3" label="标签价"/></el-select><el-select v-model="filters.status" clearable placeholder="销售状态" style="width:150px"><el-option :value="1" label="可售（已上架）"/><el-option :value="0" label="未上架（仍在库存）"/></el-select><el-button type="primary" @click="load">查询</el-button></div><div class="inline-actions"><el-button @click="categoryDialog=true">分类管理</el-button></div></div><div class="muted" style="margin:-4px 0 12px">商品页分类管理控制收银端分类；商品是库存中已上架销售的子集。新货品请先扫码入库或手动入库。</div><el-table :data="rows" stripe><el-table-column label="图" width="70"><template #default="s"><el-image v-if="rowImages(s.row).length" :src="rowImages(s.row)[0]" :preview-src-list="rowImages(s.row)" fit="cover" class="goods-thumb" preview-teleported/><span v-else class="muted">—</span></template></el-table-column><el-table-column v-for="c in columns" :key="c.key" :prop="c.key" :label="c.label"><template #default="s">{{c.key==='price_type'?priceText(s.row[c.key]):c.key==='status'?(s.row[c.key]===1?'可售':'未上架（库存）'):s.row[c.key]??'-'}}</template></el-table-column><el-table-column label="操作" width="190"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑销售属性</el-button><el-button link :type="s.row.status===1?'danger':'success'" @click="toggle(s.row)">{{s.row.status===1?'下架（留在库存）':'上架销售'}}</el-button></template></el-table-column></el-table></section>
<el-dialog v-model="dialog" title="编辑库存货品销售属性" width="600px"><el-form :model="form" label-width="95px"><el-form-item label="条码"><el-input v-model="form.barcode" disabled/></el-form-item><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="一级分类"><el-select v-model="form.parentCategoryId" disabled style="width:100%"><el-option v-for="c in roots" :key="c.category_id" :value="c.category_id" :label="c.name"/></el-select></el-form-item><el-form-item label="二级子类"><el-select v-model="form.categoryId" disabled style="width:100%"><el-option v-for="c in childrenOf(form.parentCategoryId)" :key="c.category_id" :value="c.category_id" :label="c.name"/></el-select></el-form-item><el-form-item label="计价方式"><el-radio-group v-model="form.priceType"><el-radio :value="1">按克</el-radio><el-radio :value="2">按件</el-radio><el-radio :value="3">标签价</el-radio></el-radio-group></el-form-item><el-form-item v-if="Number(form.priceType)===1" label="贵金属类型"><el-select v-model="form.goldType" filterable><el-option v-for="t in goldTypes" :key="t.type_id||t.type_name" :value="t.type_name" :label="t.type_name"/></el-select></el-form-item><el-form-item label="克重"><el-input-number v-model="form.weight" :min="0" :precision="3"/></el-form-item><el-form-item label="成本价"><el-input-number v-model="form.costPrice" :min="0" :precision="2"/></el-form-item><el-form-item label="售价"><el-input-number v-model="form.salePrice" :min="0" :precision="2"/></el-form-item><el-form-item label="库存"><el-input-number v-model="form.stock" disabled/></el-form-item><el-form-item label="商品图"><div class="img-field"><el-image v-if="rowImages(form).length" :src="rowImages(form)[0]" :preview-src-list="rowImages(form)" fit="cover" class="goods-thumb big" preview-teleported/><input type="file" accept="image/*" @change="image"/><span class="muted" v-if="rowImages(form).length">点击图片放大；重新选文件即替换</span><span class="muted" v-else>未上传</span></div></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
<CategoryManagementDialog v-model="categoryDialog" @changed="onCategoriesChanged" />
</template>
<style scoped>
.goods-thumb { width:48px; height:48px; border-radius:4px; border:1px solid var(--el-border-color-lighter); cursor:zoom-in; display:block; }
.goods-thumb.big { width:64px; height:64px; border-radius:6px; }
.img-field { display:flex; align-items:center; gap:10px; flex-wrap:wrap; }
</style>
