package com.dajin.system.system;
import com.dajin.system.common.*; import com.dajin.system.config.RequireRoles; import com.dajin.system.config.SyncWebSocketHandler; import com.dajin.system.persistence.*; import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import org.springframework.jdbc.core.namedparam.*; import org.springframework.web.bind.annotation.*; import javax.servlet.http.*; import java.util.*;
@RestController @RequestMapping("/api/system") public class SystemController {private final DbSupport db;private final SysConfigMapper configMapper;private final SyncWebSocketHandler ws;public SystemController(DbSupport db,SysConfigMapper configMapper,SyncWebSocketHandler ws){this.db=db;this.configMapper=configMapper;this.ws=ws;}
 @GetMapping("/store-info") public ApiResponse<?> store(HttpServletRequest r){return ApiResponse.ok(db.one("select * from sys_store where store_id=:s",Map.of("s",db.store(r))));}
 @GetMapping("/print-template") public ApiResponse<?> templates(HttpServletRequest r){return ApiResponse.ok(db.list("select * from print_template where store_id=:s order by template_id",Map.of("s",db.store(r))));}
 @GetMapping("/config") public ApiResponse<?> config(HttpServletRequest r){return ApiResponse.ok(configMapper.selectList(new LambdaQueryWrapper<SysConfigEntity>().eq(SysConfigEntity::getStoreId,db.store(r)).eq(SysConfigEntity::getEnabled,1).orderByAsc(SysConfigEntity::getConfigSort)));}
 @GetMapping("/target") public ApiResponse<?> target(HttpServletRequest r){String value=db.jdbc().queryForObject("select coalesce(max(case when config_key='monthly_sales_target' then config_value end),'0') from sys_config where store_id=:s and enabled=1",Map.of("s",db.store(r)),String.class);return ApiResponse.ok(Map.of("monthlySalesTarget",new java.math.BigDecimal(value)));}
 @PutMapping("/target") @RequireRoles({"ADMIN","MANAGER"}) public ApiResponse<?> setTarget(@RequestBody Map<String,Object> body,HttpServletRequest r){java.math.BigDecimal value;try{value=new java.math.BigDecimal(String.valueOf(body.get("monthlySalesTarget")));}catch(Exception e){throw new BusinessException(400422,"目标金额格式不正确");}if(value.signum()<0)throw new BusinessException(400422,"目标金额不能为负");long storeId=db.store(r);MapSqlParameterSource p=new MapSqlParameterSource().addValue("s",storeId).addValue("v",value.toPlainString());int updated=db.jdbc().update("update sys_config set config_value=:v,update_time=now() where store_id=:s and config_key='monthly_sales_target'",p);if(updated==0)db.jdbc().update("insert into sys_config(store_id,config_group,config_key,config_value,description,config_sort,enabled) values(:s,'TARGET','monthly_sales_target',:v,'本月销售目标',0,1)",p);Map<String,Object> event=Map.of("storeId",storeId,"monthlySalesTarget",value);ws.broadcast("TARGET_UPDATED",event);ws.broadcast("REPORT_UPDATED",event);return ApiResponse.ok(Map.of("monthlySalesTarget",value));}
}
